### ISSUE TITLE
Uncaught exception when running sample code.

### ISSUE THREAD

**Issue by nelsong** [brieucthomas/ergast-client#1]
PHP Fatal error:  Uncaught exception 'Doctrine\Common\Annotations\AnnotationException' with message '[Semantical Error] The annotation "@JMS\Serializer\Annotation\XmlRoot" in class BrieucThomas\ErgastClient\Entity\Response does not exist, or could not be auto-loaded.' in /Users/nguerrero/code/prueba/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
Stack trace:
#0 /Users/nguerrero/code/prueba/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')
#1 /Users/nguerrero/code/prueba/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation()
#2 /Users/nguerrero/code/prueba/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations()
#3 /Users/nguerrero/code/prueba/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php( in /Users/nguerrero/code/prueba/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 54

The weird thing is that the app runs all the tests correctly from the git clone.

**Comment by brieucthomas** [comment]
Hi,

There are some troubles with the Doctrine Annotations and the autoloading : http://stackoverflow.com/questions/14629137/jmsserializer-stand-alone-annotation-does-not-exist-or-cannot-be-auto-loaded/14646475#14646475

Tests runs correclty because the PHPUnit bootstrap file registers an autoloading for annotations:
https://github.com/brieucthomas/ergast-client/blob/master/tests/bootstrap.php#L7

**Comment by nelsong** [comment]
That worked perfect, thanks a million.
